import java.util.Random;
public class Randomness {
    public static void main(String[] args) {
       /*Here we create a random number using the Math class of the Java library. This is the first way to do it.
       You don't need to create an object of Math, you can just use Math.random() directly.
        */
        double zufallsKommazahl = Math.random();
        // Zahl zw 0 und 1
        int ganzeZufallszahl = (int) (Math.random() * 100);
        // Zahl zw 0 und 99

        System.out.println(zufallsKommazahl);
        System.out.println(ganzeZufallszahl);

        System.out.println("This is our random number generated by the randomGenerator:");
        System.out.println(generateRandom());

        System.out.println("This is our random number generated by the randomGenerator with an upper bound");
        System.out.println(generateRandomWithUpperBound());
    }
    /*This method generates a random number using the Random class from the Java library.
    * It's te second way to do it.
    * You have to generate a new Random object in order to use it.
    * Then you can call any method the library has on the object, here we used nextInt();
    */
    public static int generateRandom(){
        Random randomgenerator = new Random();
        int zufallsZahl = randomgenerator.nextInt();
        return zufallsZahl;
    }

    /*This method generates a random number using the Random class from the Java library
     * You have to generate a new Random object in order to use it.
     * Then you can call any method the library has on the object, here we used nextInt() with an upper bound,
     * meaning that it will only create random numbers up to 49.
     */
    public static int generateRandomWithUpperBound(){
        Random randomgenerator = new Random();
        int zufallsZahl = randomgenerator.nextInt(50);
        return zufallsZahl;
    }
}
